### ISSUE TITLE
Support local actions (without token?)

### ISSUE THREAD

**Issue by rob-valor** [YunaBraska/github-workflow-plugin#16]
**What happened?**
actions in same repository (not pushed to GitHub) are not _found_ and requests for a GitHub token. So no plugin support during development. Did not add token yet, but it should work without. All local and GH public files are accessible without token. 

**How can we reproduce the issue?**
Add an action in same repository and don't add token. Reference that action in an other action or workflow in same repository.

**Expected behavior**
Pick up the action because there is no Github access required as the file is not pushed yet.

**Screenshots**
![image](https://github.com/YunaBraska/github-workflow-plugin/assets/56135014/c169fe03-2bda-44bb-970b-d7e1c900bc3d)

**Additional context**
Plugin seems to be completely broken if no GH token is provided. This is not expected behavior.

**Comment by YunaBraska** [comment]
Thx @rob-valor 
It's not **"completely broken"** :) 
This plugin is pretty new, and I am currently collecting use cases to provide composite actions support. 
Therefore, your input is really important.
It might work when adding **`./.github`** as prefix  _(e.g. `./.github/your_action.yaml`)_ 
Anyway, I will work on that.

**Comment by rob-valor** [comment]
I've been trying several paths and locations but I don't get any plugin support. I'm using workflows `<repo>/.github/workflows/<workflow-name>.yaml` of which one references an other one and actions `<repo>/<action-name>/action.yaml` and also there some references from one to another.

When using the checkout action, I have plugin support. So, indeed, it's not _completely broken_ :hand_over_mouth:

**Comment by YunaBraska** [comment]
The new Version [2.2.7](https://plugins.jetbrains.com/plugin/21396-github-workflow/versions/stable/383062) will have a better support for local actions.
Syntax Highlighting and also Code Completion for action.yml files is on my list. Therefore, not every Intellisense will work.

**Comment by YunaBraska** [comment]
[2.2.7](https://plugins.jetbrains.com/plugin/21396-github-workflow/versions/stable/383062) is published. It should work now

**Comment by rob-valor** [comment]
I'm unable to verify this because of #22
