### ISSUE TITLE
Allow usage without GitHub token

### ISSUE THREAD

**Issue by rob-valor** [YunaBraska/github-workflow-plugin#22]
**What happened?**
update to 2.2.7 causes login popup to appear multiple times (7 times to be more specific) when I try to reference an action (`uses: <the action>`). This makes it very difficult to add a step that uses an action.

I have to disable the plugin to avoid getting that login popup.

**How can we reproduce the issue?**
* Don't login or add a GitHub token
* add a step that uses an action

**Operating System**
Ubuntu

**Project Version**
2.2.7

**Expected behavior**
Be able to use the plugin without getting that popup every time. Just accept the fact that i choose not to add a token and remember that choice. (Its an Organization user and need to check the policy)

**Screenshots**
![image](https://github.com/YunaBraska/github-workflow-plugin/assets/56135014/0e83f72b-54b6-48ad-89a8-4ee0373f9338)

**Comment by YunaBraska** [comment]
Thx, its a good Idea to remember this choice :)

**Comment by YunaBraska** [comment]
Thx for reporting. It should be fixed now , you can disable checks for your unresolved actions [3.0.0](https://plugins.jetbrains.com/plugin/21396-github-workflow/versions/stable/403332) Feel free to open new tickets on any bugs or feature requests.
