### ISSUE TITLE
Possibility to ignore output variable validation for certain actions

### ISSUE THREAD

**Issue by thake** [YunaBraska/github-workflow-plugin#33]
**Is your feature request related to a problem? Please describe.**
I'm using the [dotenv-action](https://github.com/marketplace/actions/dotenv-action), which makes properties available as step outputs. Because the plugin's meta-data can't have information on the used properties, this plugin cannot correctly validate the actions output.

**Describe the solution you'd like**
I want to be able to disable output variable validation for specific actions so that I don't get any false positives.

**Describe alternatives you've considered**
None so far

**Operating System**
> N/A

**Project Version**
> N/A

**Comment by YunaBraska** [comment]
Greetings @thake,
Thank you for the request. I had not yet thought of this case.
A little brainstorming together:
1) A similar function is already built in for unrecognised actions. See screenshot. Would this option be sufficient if I always display this option?
2) Would you suggest ignoring single output elements, or just disable the validation of all output elements?
3) Visualisation: should the output variables get a weak warning to show that they are not validated, or would that interfere?

![screenshot_25244c07-68f5-43c9-a9ec-a8896e09b0a6](https://github.com/YunaBraska/github-workflow-plugin/assets/13748223/4a223711-e266-43ed-93dd-93faf08cd9a8)

**Comment by thake** [comment]
Hey @YunaBraska, thanks for your quick response!
Here are my comments:
1. That would be sufficient and consistent. I like it :)
2. Leave it to the user. So offer both options. Either ignore a single output variable or all output variables of a specific action.
3. A weak warning with a tooltip seems very sensible. This is also a good place to offer a function to undo ignoring the variable.

**Comment by YunaBraska** [comment]
Back from vacation.... 
I added now the ability to disable checks for `inputs` and `outputs`. 
The weak warning is not implemented, cause it looks pretty ugly on many outputs.
What do you think? Does it solve your issue?

### Inputs
![Screenshot 2023-10-28 at 18 13 57](https://github.com/YunaBraska/github-workflow-plugin/assets/13748223/12579413-674e-4567-971a-134ffbb7eef8)

### Outputs
![Screenshot 2023-10-28 at 18 12 57](https://github.com/YunaBraska/github-workflow-plugin/assets/13748223/18a0a916-32db-4939-9b82-f239cc1bba1f)
![Screenshot 2023-10-28 at 18 13 13](https://github.com/YunaBraska/github-workflow-plugin/assets/13748223/d5132e4c-fd6a-44d0-957f-f489185ca326)

**Comment by thake** [comment]
@YunaBraska I totally like it :) Thank you!
