### ISSUE TITLE
Does it work on IntelliJ IDEA 2023.3 (beta) ? 

### ISSUE THREAD

**Issue by mhorioka** [YunaBraska/github-workflow-plugin#44]
**What do you want to achieve?**

I Installed Github Workflow 3.2.1. Seems like syntax highlighting is not working with GH workflow yaml file.
<img width="1267" alt="スクリーンショット 2023-11-21 16 21 16" src="https://github.com/YunaBraska/github-workflow-plugin/assets/695286/ad1bbaf0-6b0f-4f6d-b6b7-ac27d66c5f74">

Can you advise what can be wrong? Maybe I repeated picking up different json schema in the editor setting at the bottom and it breaks something?

**What did you try already?**
Hi, I'm on IntelliJ IDEA 2023.3 Beta on macOS 14.1.1
Install the plugin
Open a test project https://github.com/mhorioka/fizzbuzz_github_actions

**Comment by YunaBraska** [comment]
What issue do you have? The Plugin seems to be loaded as far as I can see from your screenshot. The GitHub icons are on the files, and the syntax highlighting started to underline and mark the actions to make them clickable. Next to it, you have a refresh button in case the action has some issues. I probably have no highlighting for `matrix.os` that's right. But when you misspell something like in your var `${{steps.npm-cache.outputs.dir}}`, it should be highlighted then, and also it should give you code completion

**Comment by mhorioka** [comment]
@YunaBraska thank you for your confirmation!
- I had an impression that highlighting does not work because I don't see any green colored text. But seems like it gets green for quoted literals only. So works as expected
- I expected not only highlighting but also code completion for "matrix.os".  If it's not supported now, then it's ok.

**Comment by YunaBraska** [comment]
Cool, I will add `matrix.os` on my list to implement 👍
