### ISSUE TITLE
Rider not supported anymore 

### ISSUE THREAD

**Issue by SimonSchwendele** [YunaBraska/github-workflow-plugin#5]
## **What happened?**
The updated version 2.0.0 cant be used with Rider anymore.

As seen on [the marketplace](https://plugins.jetbrains.com/plugin/21396-github-workflow/versions/stable/373140) Rider is not supported anymore due to the missing dependency `com.intellij.java`

![image](https://github.com/YunaBraska/github-workflow-plugin/assets/86782769/29356d17-33e3-47fb-a4f2-64c4473f82d6)

**Comment by YunaBraska** [comment]
Fist: Thx @SimonSchwendele for your support!
I was the same surprised as you today seeing this.
2.0.1 Is already in review and will fix that.

**Comment by YunaBraska** [comment]
Job's done 📦
