### ISSUE TITLE
Not working with IntelliJ IDEA 2023.3.1 (Ultimate Edition)

### ISSUE THREAD

**Issue by vlcekvv** [YunaBraska/github-workflow-plugin#51]
I am not sure whether I need help or I should report a bug, but the plugin doesn't seem to work for me.
My build version on IntelliJ: #IU-233.11799.300, built on December 12, 2023

**What happened?**
E.g. I do not see any completion:
![image](https://github.com/YunaBraska/github-workflow-plugin/assets/38580438/f9e81a86-deff-4148-b2c4-b3c76c2263b1)

**How can we reproduce the issue?**
I have the plugin installed, everything seems to be fine:
![image](https://github.com/YunaBraska/github-workflow-plugin/assets/38580438/a59db0d8-b228-4c6c-841c-916e13682755)

But the plugin does not work.

**Operating System**
MacOS 14.1.2 (23B92) - Sonoma

**Plugin Version**
3.2.1

**IDE Name and Version**
IntelliJ IDEA 2023.3.1 (Ultimate Edition)
Build #IU-233.11799.300, built on December 12, 2023

**Comment by YunaBraska** [comment]
Hey. Lets have a look.
1) do the yaml files have the GitHub symbol added?
2) there is no parameter starting with `dis` so there is no completion for it
![Screenshot 2024-01-11 at 17 43 57](https://github.com/YunaBraska/github-workflow-plugin/assets/13748223/4f898833-83a1-405f-8997-44712c13d2de)
