### ISSUE TITLE
Share `.idea` folder

### ISSUE THREAD

**Issue by LecrisUT** [YunaBraska/github-workflow-plugin#60]
Can you help setup and share the work environment with the `.idea` folder?
- Java SDK setup
- Some configuration based on `Plugin DevKit`
- Extended configurations, e.g. `runIde -PplatformVersion=2024.1` to setup and run various versions

**Comment by YunaBraska** [comment]
I did not set up my run configurations. So this was coming automatically by IntelliJ Probably through the setup of the SDK https://plugins.jetbrains.com/docs/intellij/setting-up-theme-environment.html#add-jdk-and-intellij-platform-plugin-sdk _(oh wow we can use Java 21 now)_

That's my setup:
![Screenshot 2024-04-12 at 10 55 38](https://github.com/YunaBraska/github-workflow-plugin/assets/13748223/e8416a91-e588-43a1-bfe6-9d24b7d67e17)
![Screenshot 2024-04-12 at 10 55 08](https://github.com/YunaBraska/github-workflow-plugin/assets/13748223/663464cd-2c58-4cd0-bc07-f1064d172322)
![Screenshot 2024-04-12 at 10 58 47](https://github.com/YunaBraska/github-workflow-plugin/assets/13748223/c8523ce4-57a6-44f6-a142-1129f9318ba1)

**Comment by YunaBraska** [comment]
I found a file: 

`.run/Run Plugin.run.xml`
```
<component name="ProjectRunConfigurationManager">
  <configuration default="false" name="Run Plugin" type="GradleRunConfiguration" factoryName="Gradle">
    <log_file alias="idea.log" path="$PROJECT_DIR$/build/idea-sandbox/system/log/idea.log" />
    <ExternalSystemSettings>
      <option name="executionName" />
      <option name="externalProjectPath" value="$PROJECT_DIR$" />
      <option name="externalSystemIdString" value="GRADLE" />
      <option name="scriptParameters" value="" />
      <option name="taskDescriptions">
        <list />
      </option>
      <option name="taskNames">
        <list>
          <option value="runIde" />
        </list>
      </option>
      <option name="vmOptions" value="" />
    </ExternalSystemSettings>
    <ExternalSystemDebugServerProcess>true</ExternalSystemDebugServerProcess>
    <ExternalSystemReattachDebugProcess>true</ExternalSystemReattachDebugProcess>
    <DebugAllEnabled>false</DebugAllEnabled>
    <RunAsTest>false</RunAsTest>
    <method v="2" />
  </configuration>
</component>
```

`.run/Run Plugin Tests.run.xml`
```
<component name="ProjectRunConfigurationManager">
  <configuration default="false" name="Run Tests" type="GradleRunConfiguration" factoryName="Gradle">
    <log_file alias="idea.log" path="$PROJECT_DIR$/build/idea-sandbox/system/log/idea.log" />
    <ExternalSystemSettings>
      <option name="executionName" />
      <option name="externalProjectPath" value="$PROJECT_DIR$" />
      <option name="externalSystemIdString" value="GRADLE" />
      <option name="scriptParameters" value="" />
      <option name="taskDescriptions">
        <list />
      </option>
      <option name="taskNames">
        <list>
          <option value="check" />
        </list>
      </option>
      <option name="vmOptions" value="" />
    </ExternalSystemSettings>
    <ExternalSystemDebugServerProcess>true</ExternalSystemDebugServerProcess>
    <ExternalSystemReattachDebugProcess>true</ExternalSystemReattachDebugProcess>
    <DebugAllEnabled>false</DebugAllEnabled>
    <method v="2" />
  </configuration>
</component>

**Comment by LecrisUT** [comment]
Ok, I will try to get it setup on my side as well and then I will make a PR to vcs the `.idea` folder. I am not familiar enough with Java, so can you advice on a safe SDK to use?

**Comment by YunaBraska** [comment]
The `.idea` folder should not be checked in as there are often files which depend on your local environment and user. I can see that the run folder is already checkedin. https://github.com/YunaBraska/github-workflow-plugin/tree/main/.run

So you just need to set up your SDK like on my [comment](https://github.com/YunaBraska/github-workflow-plugin/issues/60#issuecomment-2051338701). You can start with Java 17 this is LTS version. We can update the project to java 21 later. But step by step

**Comment by YunaBraska** [comment]
You can also join the [slack community](https://plugins.jetbrains.com/slack/) if you prefer to chat with me in real time ;)
