### ISSUE TITLE
Schema updates

### ISSUE THREAD

**Issue by LecrisUT** [YunaBraska/github-workflow-plugin#61]
After running `gradelw check` I've noticed the schemas are updated. Not sure where this is defined, but this should be a separate task that we can run in the CI to keep it up to date.

**Comment by YunaBraska** [comment]
They are refreshing with the tests.

**Comment by LecrisUT** [comment]
Are they shipped and used by the plugin, or only by the tests?

**Comment by YunaBraska** [comment]
the tests are updating the schemas which are used then by the plugin for the IDE. I have seen that 2024 has these schemas already, but i have no idea about other IDE's. They don't harm anyone, so i would keep them for now and focus on more urgend things first
