### ISSUE TITLE
Support for dependabot.yml configuration files

### ISSUE THREAD

**Issue by YannCebron** [YunaBraska/github-workflow-plugin#7]
Provide code insight (validation, completion, ..) 
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#enabling-github-dependabot-version-updates

**Comment by YunaBraska** [comment]
Schema Validation for dependabot is added in 2.2.0
I also added the automatic error reporter in 2.1.0
Thx @YannCebron for your help :)
